
# AIRR Knowledge extract, transform, validate, load pipeline

# database connection info
include .env
PG_CONN=postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/postgres
PG_AK_CONN=postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DB)
PG_DISPLAY_CONN=postgresql://$(POSTGRES_USER):XXXXXX@$(POSTGRES_HOST)/$(POSTGRES_DB)
export IMPORT_DATA
export PG_AK_CONN
export POSTGRES_DB

# docker maps this path to the local host where the data resides
AK_DATA ?= /ak_data
export AK_DATA
AK_IMPORT_DATA=$(AK_DATA)/data-extract
export AK_IMPORT_DATA
AK_TRANSFORM_DATA=$(AK_DATA)/ak-transform-data/$(POSTGRES_DB)
export AK_TRANSFORM_DATA

# data import directories
ADC_IMPORT_DATA=$(AK_IMPORT_DATA)/vdjserver-adc-cache/cache
export ADC_IMPORT_DATA
ADC_TRANSFORM_DATA=$(AK_TRANSFORM_DATA)/adc
export ADC_TRANSFORM_DATA

IEDB_IMPORT_DATA=$(AK_IMPORT_DATA)/iedb
export IEDB_IMPORT_DATA
IEDB_TRANSFORM_DATA=$(AK_TRANSFORM_DATA)/iedb
export IEDB_TRANSFORM_DATA

VDJBASE_DATA=$(AK_DATA)/vdjbase

VDJBASE_IMPORT_DATA=$(AK_IMPORT_DATA)/vdjbase
export VDJBASE_IMPORT_DATA

VDJBASE_TRANSFORM_DATA=$(AK_TRANSFORM_DATA)/vdjbase
export VDJBASE_TRANSFORM_DATA

# transformed data ready for DB load
# inside docker
AK_DATA_LOAD=$(AK_DATA)/ak-data-load/$(POSTGRES_DB)
export AK_DATA_LOAD
# outside docker
AIRRKB_LOAD=$(IMPORT_DATA)/ak-data-import/ak-data-load/$(POSTGRES_DB)
export AIRRKB_LOAD


export AK_DATA_LOAD

# ADC study lists are generated by the extraction script
ADC_CACHE_LIST := $(shell python3 adc_study_list.py adc)

ADC_TRANSFORM_TARGETS := $(addprefix adc-transform-,$(ADC_CACHE_LIST))
ADC_TRANSFORM_REPERTOIRE_TARGETS := $(addprefix adc-transform-repertoire-,$(ADC_CACHE_LIST))
ADC_TRANSFORM_CHAIN_TARGETS := $(addprefix adc-transform-chain-,$(ADC_CACHE_LIST))
ADC_QUERY_TARGETS := $(addprefix query-adc-,$(ADC_CACHE_LIST))
ADC_LOAD_TARGETS := $(addprefix load-adc-data-,$(ADC_CACHE_LIST))

# VDJBASE study lists are generated by the extraction script

VDJBASE_CACHE_LIST := $(shell python3 adc_study_list.py vdjbase)

VDJBASE_TRANSFORM_TARGETS := $(addprefix vdjbase-transform-,$(VDJBASE_CACHE_LIST))
VDJBASE_TRANSFORM_REPERTOIRE_TARGETS := $(addprefix vdjbase-transform-repertoire-,$(VDJBASE_CACHE_LIST))
VDJBASE_TRANSFORM_CHAIN_TARGETS := $(addprefix vdjbase-transform-chain-,$(VDJBASE_CACHE_LIST))
VDJBASE_QUERY_TARGETS := $(addprefix query-vdjbase-,$(VDJBASE_CACHE_LIST))
VDJBASE_LOAD_TARGETS := $(addprefix load-vdjbase-data-,$(VDJBASE_CACHE_LIST))

# note: "help" MUST be the first target in the file, so
# when the user types "make" they get help info by default
help:
	@echo ""
	@echo "AIRR Knowledge ETVL pipeline"
	@echo "------------------------------------------------------------"
	@echo "Using DB: $(PG_DISPLAY_CONN)"
	@echo "Host location of ak-data-import folder: $(IMPORT_DATA)"
	@echo ""
	@echo "make docker             -- Build docker image"
	@echo ""
	@echo "Utility functions (within docker)"
	@echo "make show-paths         -- Show data paths for import, transform and load"
	@echo "make list-extract       -- List all repository data extract files"
	@echo "make list-transform     -- List all transform output files"
	@echo "make list-load          -- List DB load files"
	@echo "make list-vdjbase-cache -- List VDJbase study cache IDs"
	@echo "make list-adc-cache     -- List ADC study cache IDs"
	@echo "make ak-schema          -- Build and install ak-schema submodule"
	@echo ""
	@echo "make transform-clean    -- Remove generated files from data transform"
	@echo "make load-clean         -- Remove generated files for DB load"
	@echo "------------------------------------------------------------"
	@echo ""
	@echo "Data Extract workflow"
	@echo "  (run within docker)"
	@echo "------------------------------------------------------------"
	@echo "make extract-ogrdb      -- Extract data from OGRDB"
	@echo "make extract-iedb       -- Extract data from IEDB"
	@echo "make extract-adc        -- Extract data from VDJServer's ADC cache"
	@echo "make extract-irad       -- Extract data from IRAD"
	@echo "make extract-vdjbase    -- Extract data from VDJbase"
	@echo "make data-fixes         -- Fix unresolved errors in repository data"
	@echo "------------------------------------------------------------"
	@echo ""
	@echo "Ontology workflow"
	@echo "  (run outside docker)"
	@echo "------------------------------------------------------------"
	@echo "make ak-ontology        -- Build AK ontology"
	@echo "make ak-ontology-utsw   -- Build AK ontology (using UTSW proxy config)"
	@echo "make ontology-export    -- Generate ontology export files"
	@echo "------------------------------------------------------------"
	@echo ""
	@echo "Data Transform workflow"
	@echo "  (run within docker)"
	@echo "------------------------------------------------------------"
	@echo "make ogrdb-transform    -- Transform OGRDB germlines"
	@echo ""
	@echo "make iedb-transform     -- Transform IEDB TCR and BCR export files"
	@echo "make iedb-query         -- Generate query objects for transformed IEDB data"
	@echo "make iedb-copy          -- Copy transformed IEDB data to DB load directory"
	@echo ""
	@echo "make irad-bcr           -- Transform IRAD BCRs"
	@echo ""
	@echo "make vdjbase-transform                      -- Transform VDJbase repertoires/genotypes for all studies"
	@echo "make vdjbase-transform-repertoire           -- Transform VDJBASE repertoires for all studies"
	@echo "make vdjbase-transform-CACHE_ID             -- Transform VDJBASE repertoires and rearrangements for study CACHE_ID"
	@echo "make vdjbase-transform-repertoire-CACHE_ID  -- Transform VDJBASE repertoires for study CACHE_ID"
	@echo "make vdjbase-transform-chain-CACHE_ID       -- Transform VDJBASE rearrangements for study CACHE_ID"
	@echo ""
	@echo "make query-vdjbase                          -- Create and save query object for all studies"
	@echo "make query-vdjbase-CACHE_ID                 -- Create and save query object for study CACHE_ID"
	@echo "make vdjbase-copy                           -- Copy transformed VDJBASE data to DB load directory"
	@echo ""
	@echo "make adc-transform                      -- Transform ADC repertoires and rearrangements for all studies"
	@echo "make adc-transform-repertoire           -- Transform ADC repertoires for all studies"
	@echo "make adc-transform-CACHE_ID             -- Transform ADC repertoires and rearrangements for study CACHE_ID"
	@echo "make adc-transform-repertoire-CACHE_ID  -- Transform ADC repertoires for study CACHE_ID"
	@echo "make adc-transform-chain-CACHE_ID       -- Transform ADC rearrangements for study CACHE_ID"
	@echo ""
	@echo "make query-adc                          -- Create and save query object for all studies"
	@echo "make query-adc-CACHE_ID                 -- Create and save query object for study CACHE_ID"
	@echo "make adc-copy                           -- Copy transformed ADC data to DB load directory"
	@echo ""
	@echo "make ontology-copy      -- Copy ontology export files to DB load directory"
	@echo "------------------------------------------------------------"
	@echo ""
	@echo "    Database Loads"
	@echo "  (run outside docker)"
	@echo "------------------------------------------------------------"
	@echo "make drop-sql-airrkb    -- Drop airrkb (version: $(POSTGRES_DB))"
	@echo "make create-sql-airrkb  -- Create airrkb (version: $(POSTGRES_DB))"
	@echo ""
	@echo "make load-ontology      -- Load ontology data into airrkb"
	@echo ""
	@echo "make load-iedb-data     -- Load IEDB data into airrkb (version: $(POSTGRES_DB))"
	@echo ""
	@echo "make load-vdjbase-data-CACHE_ID  -- Load ADC data into airrkb for study CACHE_ID"
	@echo "make load-vdjbase-data           -- Load all ADC data into airrkb"
	@echo ""
	@echo "make load-adc-data-CACHE_ID  -- Load ADC data into airrkb for study CACHE_ID"
	@echo "make load-adc-data           -- Load all ADC data into airrkb"
	@echo "------------------------------------------------------------"
	@echo ""

# build docker image
docker:
	@echo "Building docker image"
	docker build . -t airrknowledge/ak-etvl:$(POSTGRES_DB)

check-docker:
	@if [ -z "$(AKC_DOCKER)" ]; then echo "MUST BE RUN WITHIN DOCKER"; exit 1; fi

outside-docker:
	@if [ -z "$(AKC_DOCKER)" ]; then exit 0; else echo "MUST BE RUN OUTSIDE OF DOCKER"; exit 1; fi

show-paths:
	@echo "------------------------------------------------------------"
	@echo "Using DB: $(PG_DISPLAY_CONN)"
	@echo "Host location of ak-data-import folder: $(IMPORT_DATA)"
	@echo "------------------------------------------------------------"
	@echo "Paths inside docker:"
	@echo ""
	@echo "               AK_DATA = $(AK_DATA) [host: $(IMPORT_DATA)]"
	@echo "        AK_IMPORT_DATA = $(AK_IMPORT_DATA)"
	@echo "     AK_TRANSFORM_DATA = $(AK_TRANSFORM_DATA)"
	@echo ""
	@echo "       ADC_IMPORT_DATA = $(ADC_IMPORT_DATA)"
	@echo "    ADC_TRANSFORM_DATA = $(ADC_TRANSFORM_DATA)"
	@echo ""
	@echo "      IEDB_IMPORT_DATA = $(IEDB_IMPORT_DATA)"
	@echo "   IEDB_TRANSFORM_DATA = $(IEDB_TRANSFORM_DATA)"
	@echo ""
	@echo "      IRAD_IMPORT_DATA = $(IRAD_IMPORT_DATA)"
	@echo "   IRAD_TRANSFORM_DATA = $(IRAD_TRANSFORM_DATA)"
	@echo ""
	@echo "   VDJBASE_IMPORT_DATA = $(VDJBASE_IMPORT_DATA)"
	@echo "VDJBASE_TRANSFORM_DATA = $(VDJBASE_TRANSFORM_DATA)"
	@echo "------------------------------------------------------------"
	@echo "          AK_DATA_LOAD = $(AK_DATA_LOAD)"
	@echo "           AIRRKB_LOAD = $(AIRRKB_LOAD)"
	@echo "------------------------------------------------------------"


.PHONY: ak-schema
ak-schema: check-docker
	cd ak-schema; make all; make install; make sqlddl

# generate python dataclasses from schema
ak_schema.py: check-docker ak-schema/project/linkml/ak_schema.yaml
	gen-python ak-schema/project/linkml/ak_schema.yaml > $@

list-vdjbase-cache:
	@echo VDJBASE CACHE LIST --
	@echo $(VDJBASE_CACHE_LIST)
	@echo ""
	@echo VDJBASE CACHE LOAD TARGETS --
	@echo $(VDJBASE_LOAD_TARGETS)

list-adc-cache:
	@echo ADC CACHE LIST --
	@echo $(ADC_CACHE_LIST)
	@echo ""
	@echo ADC CACHE LOAD TARGETS --
	@echo $(ADC_LOAD_TARGETS)

#
# Data extraction
#
extract-ogrdb:
	@echo "Not implemented."

extract-iedb:
	python extract_iedb.py $(IEDB_IMPORT_DATA)

extract-adc:
	python extract_adc.py $(ADC_IMPORT_DATA)

extract-irad:
	@echo "Not implemented."

extract-vdjbase:
	@echo "Downloading VDJbase data."
	# bash download_vdjbase_data.sh
	python3 extract_vdjbase.py $(VDJBASE_IMPORT_DATA)

data-fixes: check-docker
	@echo "Fixing data errors."
	python3 iReceptor_metadata_fix.py

#
# Data transform
#

# OGRDB transform
ogrdb-transform:
	@echo "Not implemented."

# IEDB transform
$(IEDB_TRANSFORM_DATA)/iedb_tsv/: check-docker
	mkdir -p $@
	mkdir -p $(IEDB_TRANSFORM_DATA)/iedb_jsonl/

iedb-transform: check-docker ak_schema.py iedb_transform.py $(IEDB_IMPORT_DATA)/tcell_full_v3.tsv $(IEDB_IMPORT_DATA)/tcr_full_v3.tsv $(IEDB_IMPORT_DATA)/bcell_full_v3.tsv $(IEDB_IMPORT_DATA)/bcr_full_v3.tsv | $(IEDB_TRANSFORM_DATA)/iedb_tsv/
	python3 $(wordlist 3,7,$^)


iedb-copy: check-docker
	mkdir -p $(AK_DATA_LOAD)/iedb
	cp -rf $(IEDB_TRANSFORM_DATA)/* $(AK_DATA_LOAD)/iedb

# IRAD transform
irad-bcr: check-docker
	@echo "Not implemented."



# ADC repertoire transform
$(ADC_TRANSFORM_DATA)/adc_tsv/: check-docker
	mkdir -p $@
	mkdir -p $(ADC_TRANSFORM_DATA)/adc_jsonl/

# ADC repertoire and rearrangement transform
# manual targets for each study is not the best
adc-transform-repertoire-%: ak_schema.py | $(ADC_TRANSFORM_DATA)/adc_tsv/
	@echo ""
	@echo "Repertoire transform"
	@echo ""
	python3 common_repertoire_transform.py adc $*

adc-transform-chain-%: ak_schema.py | $(ADC_TRANSFORM_DATA)/adc_tsv/
	@echo ""
	@echo "START: " `date`
	@echo ""
	@echo "Chain transform"
	@echo ""
	python3 common_chain_transform.py adc $*
	@echo ""
	@echo "END: " `date`
	@echo ""

adc-transform-%: ak_schema.py | $(ADC_TRANSFORM_DATA)/adc_tsv/
	@echo ""
	@echo "START: " `date`
	@echo ""
	@echo "Repertoire transform"
	@echo ""
	python3 common_repertoire_transform.py adc $*
	@echo ""
	@echo "Chain transform"
	@echo ""
	python3 common_chain_transform.py adc $*
	@echo ""
	@echo "END: " `date`
	@echo ""

adc-transform-repertoire: $(ADC_TRANSFORM_REPERTOIRE_TARGETS)
	@echo ""
	@echo "DONE"
	@echo ""

adc-transform-chain: $(ADC_TRANSFORM_CHAIN_TARGETS)
	@echo ""
	@echo "DONE"
	@echo ""

adc-transform: $(ADC_TRANSFORM_TARGETS)
	@echo ""
	@echo "DONE"
	@echo ""

adc-copy: check-docker
	mkdir -p $(AK_DATA_LOAD)/adc
	cp -rf $(ADC_TRANSFORM_DATA)/* $(AK_DATA_LOAD)/adc


# IEDB query object
iedb-query:
	@echo "Generate IEDB query objects"
	python3 query_api_script.py query-iedb

# ADC query object
query-adc-%:
	@echo "Generate ADC query objects for study cache $*"
	python query_api_script.py query-adc --cache-id=$*

query-adc: $(ADC_QUERY_TARGETS)
	@echo ""
	@echo "DONE"
	@echo ""




# # VDJbase transform
# $(VDJBASE_DATA)/vdjbase_tsv/: check-docker
# 	mkdir -p $@
# 	mkdir -p $(VDJBASE_DATA)/vdjbase_jsonl/

# VDJBASE repertoire transform
$(VDJBASE_TRANSFORM_DATA)/vdjbase_tsv/: check-docker
	mkdir -p $@
	mkdir -p $(VDJBASE_TRANSFORM_DATA)/vdjbase_jsonl/


# ADC repertoire and rearrangement transform
# manual targets for each study is not the best
vdjbase-transform-repertoire-%: ak_schema.py | $(VDJBASE_TRANSFORM_DATA)/vdjbase_tsv/
	@echo ""
	@echo "Repertoire transform"
	@echo ""
	python3 common_repertoire_transform.py vdjbase $*

vdjbase-transform-repertoire: $(VDJBASE_TRANSFORM_REPERTOIRE_TARGETS)
	@echo ""
	@echo "DONE"
	@echo ""

vdjbase-transform-chain-%: ak_schema.py | $(VDJBASE_TRANSFORM_DATA)/vdjbase_tsv/
	@echo ""
	@echo "START: " `date`
	@echo ""
	@echo "Chain transform"
	@echo ""
	python3 common_chain_transform.py vdjbase $*
	@echo ""
	@echo "END: " `date`
	@echo ""

vdjbase-transform-chain: $(VDJBASE_TRANSFORM_CHAIN_TARGETS)
	@echo ""
	@echo "DONE"
	@echo ""


vdjbase-transform-%: ak_schema.py | $(VDJBASE_TRANSFORM_DATA)/vdjbase_tsv/
	@echo ""
	@echo "START: " `date`
	@echo ""
	@echo "Repertoire transform"
	@echo ""
	python3 common_repertoire_transform.py  vdjbase $*
	@echo ""
	@echo "Chain transform"
	@echo ""
	python3 common_chain_transform.py vdjbase $*
	@echo ""
	@echo "END: " `date`
	@echo ""

vdjbase-transform: $(VDJBASE_TRANSFORM_TARGETS)
	@echo ""
	@echo "DONE"
	@echo ""

vdjbase-copy: check-docker
	mkdir -p $(AK_DATA_LOAD)/vdjbase
	cp -rf $(VDJBASE_TRANSFORM_DATA)/* $(AK_DATA_LOAD)/vdjbase


# ADC query object
query-vdjbase-%:
	@echo "Generate VDJBASE query objects for study cache $*"
	python query_api_script.py query-vdjbase --cache-id=$*

query-vdjbase: $(VDJBASE_QUERY_TARGETS)
	@echo ""
	@echo "DONE"
	@echo ""

# vdjbase-transform: ak_schema.py | $(VDJBASE_DATA)/vdjbase_tsv/
# 	python3 vdjbase_metadata_transform.py vdjbase-2025-08-231-0001-012


# Ontology exports and loads
#

.PHONY: ak-ontology
ak-ontology: outside-docker
	cd ak-ontology/src/ontology; sh run.sh make

.PHONY: ak-ontology
ak-ontology-utsw: outside-docker
	cd ak-ontology/src/ontology; cp run.sh.conf.utsw run.sh.conf; sh run.sh make

.PHONY: ontology-export
ontology-export: outside-docker
	cd ak-ontology/src/ontology; sh run.sh make all_exports

.PHONY: ontology-copy
ontology-copy: check-docker
	mkdir -p $(AK_DATA_LOAD)/ontology
	cp -rf ak-ontology/src/ontology/exports/*.csv $(AK_DATA_LOAD)/ontology

#
# Database loads
#

list-extract: check-docker
	find $(AK_IMPORT_DATA) -type d -print

list-transform: check-docker
	find $(AK_TRANSFORM_DATA) -type d -print

list-load: check-docker
	find $(AK_DATA_LOAD) -type d -print

create-sql-airrkb: outside-docker
	docker run -v $(PWD):/work --network ak-db-network -it postgres:16 psql $(PG_CONN) -c "create database $(POSTGRES_DB);"
	docker run -v $(PWD):/work --network ak-db-network -it postgres:16 psql $(PG_AK_CONN) -f /work/ak-schema/project/sqlddl/ak_schema.sql
	docker run -v $(PWD):/work --network ak-db-network -it postgres:16 psql $(PG_AK_CONN) -f /work/ak-schema/project/sqlddl/ak_schema_alter.sql
#	docker run -v $(PWD):/work --network ak-db-network -it postgres:16 psql $(PG_AK_CONN) -f /work/ak-schema/project/sqlddl/ak_schema_modify.sql
#	docker run -v $(PWD):/work --network ak-db-network -it postgres:16 psql $(PG_AK_CONN) -f /work/ak-schema/project/sqlddl/ak_schema_postgres.sql

drop-sql-airrkb: outside-docker
	docker run -v $(PWD):/work --network ak-db-network -it postgres:16 psql $(PG_CONN) -c "drop database $(POSTGRES_DB);"

load-ontology: outside-docker
	@bash ontology_load.sh BiomedicalInvestigations
	@bash ontology_load.sh Cells
	@bash ontology_load.sh Diseases
	@bash ontology_load.sh Diseases ONTIE_Diseases
	@bash ontology_load.sh PhenotypeAndTraits
	@bash ontology_load.sh TaxonomicSpecies
	@bash ontology_load.sh TaxonomicSpecies ONTIE_organisms
	@bash ontology_load.sh UberAnatomy
	@bash ontology_load.sh Units

load-iedb-data: outside-docker
	@bash iedb_load.sh
	@bash query_assay_load.sh iedb/iedb_jsonl

load-adc-data-%: outside-docker
	@bash adc_load.sh $*
	@bash query_assay_load.sh adc/adc_jsonl/$*

load-adc-data: $(ADC_LOAD_TARGETS)

load-adc-query-data-%: outside-docker
	@bash query_assay_load.sh adc/adc_jsonl/$*

load-clean: check-docker
	rm -r $(AK_DATA_LOAD)

transform-clean: check-docker
	rm -r $(AK_TRANSFORM_DATA)
